Je me presente/config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'

  get '/contact', to: 'static_pages#contact', as: 'contact/people'

  get '/about', to: 'static_pages#about'

  get 'about/toi', to: 'static_pages#toi', as: 'you'

  get 'about/ton_groupe', to: 'static_pages#ton_groupe'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Je me presente/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Je me presente/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

Je me presente/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def contact
  end

  def about
  end

  def ton_groupe
  end

  def toi
  end
  
end

Je me presente/app/helpers/application_helper.rb
module ApplicationHelper
end

Je me presente/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

Je me presente/app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>

  <head>
    <title>JeMePresente</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"/>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

Je me presente/app/views/static_pages/about.html.erb
<h1> 👩 👩 👦 👦 </h1>
<p>Find me in app/views/static_pages/about.html.erb</p>
<a href = "<%= you_path %>" > toi </a>

Je me presente/app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

Je me presente/app/views/static_pages/home.html.erb
<h1> 🏠 </h1>
<p>what a page</p>

Je me presente/app/views/static_pages/toi.html.erb
hello wolrd

Je me presente/app/views/static_pages/ton_groupe.html.erb
<h1> c'est cool </h1>
<p> zjzjdsj </p>